name: Build and Release LaTeX PDF from tags

# Source - https://stackoverflow.com/a/61892639
# Posted by riQQ, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-22, License - CC BY-SA 4.0

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /


jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main_cv.tex # Replace with your main .tex file name
          # You can specify other options here, e.g., latexmk_use_xelatex: true
          working_directory: base

      - name: Upload PDF to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Siddhant_Sharma_CV.pdf # The compiled PDF file to attach to the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
